fix: fix takePhoto not working inside an Modal
cuvent/react-native-vision-camera pull request #1021
Opened 2022-04-26 11:51 UTC by eduardoborges

## What

## Changes

## Tested on

## Related issues

2022-04-28 10:41 UTC, mrousavy commented
Hey! Thanks for your PR!

Doesn't this throw a "main thread" error? Did you test this without issues?

2022-05-05 07:55 UTC, mrousavy commented
We now probably need to call `findCameraView` using withContext to ensure it's being called from Main/UI Thread.

2022-05-05 12:14 UTC, erwanferry approved these changes

2022-05-12 12:23 UTC, eduardoborges commented
> We now probably need to call `findCameraView` using withContext to ensure it's being called from Main/UI Thread.

OK, but... Who to do this? LOL

2022-05-16 14:48 UTC, PABourdais commented
Wow nice that did fixed the `takePhoto`, I just tested it  👍

2022-05-26 14:08 UTC, eduardoborges commented
@mrousavy Can you help-me in your change request?

2022-06-08 04:43 UTC, StationSoen commented
I met same problem and fixed with this PR. thanks!

Here is patch file for [patch-package](https://github.com/ds300/patch-package)
[react-native-vision-camera+2.13.3.patch](https://gist.github.com/StationSoen/6b3f5f9dd2002384abb7d22e402f51fe)

2022-06-13 08:21 UTC, mrousavy requested changes

2022-06-13 08:21 UTC, mrousavy commented on android/src/main/java/com/mrousavy/camera/CameraViewModule.kt
> +    val ctx = mContext?.get()
Hey - I think this is unnecessary. We should just be able to pass in `reactApplicationContext` to the function below without having to create a WeakReference and access it immediately afterwards.

2022-06-30 08:26 UTC, mrousavy commented on android/src/main/java/com/mrousavy/camera/CameraViewModule.kt
>      val view = if (ctx != null) UIManagerHelper.getUIManager(ctx, viewId)?.resolveView(viewId) as CameraView? else null
Can you remove `ctx` and just use `reactApplicationContext` directly? I see no point in declaring an extra variable.

2022-07-19 21:05 UTC, eduardoborges commented
@mrousavy Can u see this PR? <3

2022-07-20 12:02 UTC, mrousavy commented
Oh I'm sorry I missed this! It somewhere got swallowed by thousands of other emails 😅 

LGTM, thank you so much for your help here!

2022-07-20 12:02 UTC, merged

2022-07-20 20:55 UTC, Eugene-Kai commented
@mrousavy publish this fix please

2022-08-08 04:38 UTC, ajithes1 commented
is this published? I'm still facing this issue.