fix: store android images with correct orientation
cuvent/react-native-vision-camera pull request #1764
Opened 2023-09-05 05:58 UTC by vonovak

## What

I noticed that Images captured on Android are not always stored with the right orientation. This is also mentioned in the release notes. I'm trying to fix that here. The PR needs testing on more devices, I just used Honor 20 Pro. If anyone can do more testing it'll be appreciated.

As a side note, this uses changes from https://github.com/mrousavy/react-native-vision-camera/pull/1749 - when they are merged the diff will be smaller.

## Changes

## Tested on

Honor 20 Pro

## Related issues

2023-09-05 12:00 UTC, mrousavy commented
Hey thanks so much for your PR man, this is amazing!

I'll test this to make sure it works for me, but just a quick tip that some Samsung devices handle orientation differently for whatever reason. See this blog post: https://medium.com/@kenodoggy/solving-image-rotation-on-android-using-camera2-api-7b3ed3518ab6

2023-09-05 13:42 UTC, vonovak commented
Haha, that's what I was afraid of 😄.
I'm new to working with cameras so this might need a few more iterations...
I'll read the blogpost and see what needs to be done, thanks 👍

2023-09-06 09:01 UTC, mrousavy requested changes
hey - quick review on the airport, left some thoughts thanks

2023-09-06 09:01 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/CameraViewManager.kt
> +      cameraViewTransactions.getOrPut(view) { ArrayList() }.add(changedProp)
tbh I don't like that syntax. Kotlin has lots of weird ways to cram things into one line instead of being expressive. Can you revert that? Thanks!

2023-09-06 09:01 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt
> +                        imageDataNeedsToBeRotatedByDegrees: Int,
I feel like this is a bit too verbose - can't we just move rotation to `this` (`CameraSession`), or does it have to be in `CameraView`? 

If not, can we rename it to something like `deviceOrientation`? I'm just not really happy with the name here

2023-09-06 09:01 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/core/CameraSession.kt
> +      val orientation = outputOrientation.toSensorRelativeOrientation(cameraCharacteristics)
Isn't that a second source of truth now? Is that still true?

2023-09-06 09:01 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/CameraView.kt
> +      if (!::deviceRotation.isInitialized) {
What's `::`? Syntax looks pretty verbose here - is that this live data thingy?

2023-09-30 13:48 UTC, mrousavy commented
Orientation is really tricky... we use #1891 to track orientation now

2023-10-02 08:04 UTC, closed without merging