Fix Frame Processor is not removed when Camera view unmount
cuvent/react-native-vision-camera pull request #1960
Opened 2023-10-10 03:16 UTC by r0b0t3d

## What
This PR fix issue frame proccessor is not removed when Camera view unmount

## Changes
- Add `componentWillUnmount` method
- Check if frame processor is not null
- Unset frame processor

## Tested on
- iPhone 7, ios 15
- I don't have physical android devices

2023-10-10 16:54 UTC, mrousavy requested changes
Hey, thanks for the PR, this is good!

Just one minor detail, let's use `this.lastFrameProcessor` as that is the source of truth of the currently in-memory FP.

2023-10-10 16:54 UTC, mrousavy commented on package/src/Camera.tsx
> +    if (this.props.frameProcessor !== null) {
```suggestion
    if (this.lastFrameProcessor !== null) {
```

2023-10-10 16:55 UTC, merged

2023-10-10 16:56 UTC, mrousavy commented
Actually on second thought, do we really need this? Was there any problem before?

If the Camera unmounts on the native side, it will delete the `FrameProcessor` instance anyways. Calling unset here is probably an unnecessary call to native...

2023-10-10 23:23 UTC, r0b0t3d commented
@mrousavy I got the issue in my local development. When the camera unmount, I still got console.log from frame processor

2023-10-11 07:51 UTC, mrousavy commented
Did it crash? Or an error?

2023-10-11 07:53 UTC, r0b0t3d commented
Not crash or error. But it's not right when frame processor is still running even if no camera active

2023-10-11 07:58 UTC, mrousavy commented
How long was it running for? When the Camera fully unmounts it will stop, maybe it will run for one or two more frames because the Camera is not fully unmounted.

Please share a screen recording or something.