Fix java.util.NoSuchElementException at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:107)
cuvent/react-native-vision-camera pull request #2266
Opened 2023-12-08 10:56 UTC by Romick2005

Android Xiaomi Redmi Note 11 Pro 5G issue:
```
Short message: An unknown error occurred while trying to start a video recording! null.
 ERROR  {"cause": {"message": null, "stacktrace": "java.util.NoSuchElementException
	at com.mrousavy.camera.extensions.RecordingSession_getRecommendedBitRateKt.getRecommendedBitRate(RecordingSession+getRecommendedBitRate.kt:107)
	at com.mrousavy.camera.core.RecordingSession.getBitRate(RecordingSession.kt:132)
	at com.mrousavy.camera.core.RecordingSession.<init>(RecordingSession.kt:37)
	at com.mrousavy.camera.core.CameraSession.startRecording(CameraSession.kt:532)
	at com.mrousavy.camera.CameraView_RecordVideoKt.startRecording(CameraView+RecordVideo.kt:34)
	at com.mrousavy.camera.CameraViewModule$startRecording$1.invokeSuspend(CameraViewModule.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
"}, "code": "capture/unknown", "message": "An unknown error occurred while trying to start a video recording! null", "userInfo": null}
```

2023-12-08 10:57 UTC, Romick2005 commented
Related with [Fix VideoProfile possibly being null #2231](https://github.com/mrousavy/react-native-vision-camera/pull/2231#issuecomment-1843465890)

2023-12-11 22:23 UTC, mrousavy requested changes
Hey - thanks for your PR! Please revert the unrelated change for now, there's a different PR for that.

The other change looks good, thanks!

2023-12-11 22:23 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/CameraDevicesManager.kt
> -  override fun hasConstants(): Boolean = true
Please revert this change

2023-12-11 22:23 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/extensions/RecordingSession+getRecommendedBitRate.kt
> +      val best = profiles.videoProfiles.filterNotNull().minByOrNull {
Good stuff, makes sense!

2023-12-12 06:58 UTC, Romick2005 commented on package/android/src/main/java/com/mrousavy/camera/CameraDevicesManager.kt
> -  override fun hasConstants(): Boolean = true
Done, sir.

2023-12-12 10:14 UTC, mrousavy commented
Awesome, thanks man - LGTM!

2023-12-12 10:15 UTC, merged