Add UPC_A support
cuvent/react-native-vision-camera pull request #2563
Opened 2024-02-15 11:37 UTC by Gambitboy

## What

This PR adds support for UPC-A barcode format.

## Changes

This PR adds the UPC-A type format to React Native, CodeType to Android and iOS, but points to EAN13 in iOS as Apple states it supports UPC-A through EAN13 [here](https://developer.apple.com/library/archive/technotes/tn2325/_index.html#//apple_ref/doc/uid/DTS40013824-CH1-IS_UPC_A_SUPPORTED_).

## Tested on

Samsung S22
iPhone X

## Related issues

Fixes #2118

2024-02-15 11:39 UTC, Gambitboy commented
I made these code changes to my app months ago, didn't test this specific PR yet can confirm by tomorrow on the 2 devices stated in the PR.

2024-02-23 18:35 UTC, mrousavy reviewed
Hey - thanks for your PR, really appreciate your contribution as this has been a fairly requested feature!

The reason I didn't implement UPC-A in the beginning was because there is no binding for it on the native iOS side.

I am not too familiar with how barcodes work, but apparently EAN_13 also scans UPC_A barcodes, so I can understand why you created this PR.

The problem I see is that when the user configures the Code Scanner to scan UPC_A codes, he will receive EAN_13 codes in the callback on iOS, which might be confusing to him if he checks for the type to make sure it is what he expects.

You know what I mean?

```ts
const codeScanner = useCodeScanner({
  codeTypes: ['upc-a'], // <-- ✅ I configure 'upc-a'
  onCodeScanned: (codes) => {
    for (const code of codes) {
      console.log(code.type) // <-- ❌ I receive 'ean-13'
    }
  }
})
```

(On Android you will receive `'upc-a'`, on iOS you will receive `'ean-13'`)

2024-02-23 18:36 UTC, mrousavy commented
Also, why is this PR still a Draft?

2024-02-23 19:16 UTC, Gambitboy commented
I forgot to undraft it.

2024-02-23 19:18 UTC, Gambitboy commented
@mrousavy  Do you think it would be worth adding a middle layer where if iOS asked for ean vs upc_a we do the conversion for them?

2024-02-26 08:21 UTC, mrousavy commented
> @mrousavy Do you think it would be worth adding a middle layer where if iOS asked for ean vs upc_a we do the conversion for them?

no. 

I'm thinking whether it would be better to make `upc-a` Android only, so it's the users job to explicitly use `ean-13` on iOS instead - then there'd be no confusion once the user read the docs....

2024-02-26 09:03 UTC, Gambitboy commented
Can we also then add that iOS supports `upc-a` through `ean-13` but they user will need to manually handle that case. Just so people know, might prevent future tickets being opened.

2024-03-12 15:02 UTC, Gambitboy commented
I've added some documentation on this issue at the bottom of the CodeScanning doc.

2024-03-12 15:05 UTC, mrousavy requested changes
update docs a bit - but good idea

2024-03-12 15:05 UTC, mrousavy commented on docs/docs/guides/CODE_SCANNING.mdx
> +You will need to keep this in mind and do the conversion from EAN-13 to UPC-A yourself. This can be done by removing the front `0` digit from the code to get a UPC-A code.
Move this above the "Next section" please.

2024-03-12 15:05 UTC, mrousavy commented on docs/docs/guides/CODE_SCANNING.mdx
> +## Special Case (UPC-A)
```suggestion
## UPC-A vs EAN-13 codes
```

2024-03-12 15:05 UTC, mrousavy commented on docs/docs/guides/CODE_SCANNING.mdx
> +})
```suggestion
const codeScanner = useCodeScanner({
  codeTypes: ['upc-a'], // <-- ✅ We configure for 'upc-a' types
  onCodeScanned: (codes) => {
    for (const code of codes) {
      console.log(code.type); // <-- ❌ On iOS, we receive 'ean-13'
    }
  }
})
```

2024-03-12 15:05 UTC, mrousavy commented on docs/docs/guides/CODE_SCANNING.mdx
> +This means the following code gives you the wrong type.
```suggestion
This means, the `upc-a` types are reported under the `ean-13` umbrella type on iOS:
```

2024-03-12 15:37 UTC, Gambitboy commented
I've made the adjustments

2024-03-12 16:48 UTC, mrousavy commented
Cool, thanks for your PR I think with the docs this makes sense.

If the PR goes green we can merge! :)

2024-03-18 13:44 UTC, Gambitboy commented
@mrousavy is this all good to merge?

2024-03-18 14:42 UTC, mrousavy commented
Ah, thanks for the ping, yes - LGTM - thank you for your contribution! ❤️

2024-03-18 14:42 UTC, merged

2024-03-24 20:06 UTC, orenagiv commented
Hey @mrousavy 
Any plans to release a version update with UPC-A any time soon?

2024-03-25 09:34 UTC, mrousavy commented
Hey - I think this is released in V4 beta!