fix: react-native-worklets-core module resolution for pnpm
cuvent/react-native-vision-camera pull request #3088
Opened 2024-07-17 14:26 UTC by ArtiomTr

## What

Currently, vision camera uses slightly incorrect logic for detecting `react-native-worklets-core` package. Current algorithm expects that `react-native-worklets-core` package will be next to `react-native` package, which is not the case with `pnpm` package manager - it creates symlinks and may create custom structure for node_modules, that will still be valid. For instance:

```
my-package
`- node_modules
   |- .pnpm
   |  |- react-native@0.73.6
   |  |  `- node_modules
   |  |     `- react-native
   |  `- react-native-worklets-core@1.3.3_react-native@0.73.6
   |     `- node_modules
   |        |- react-native ---> my-package/node_modules/.pnpm/react-native@0.73.6/node_modules/react-native
   |        `- react-native-worklets-core
   |- react-native ---> my-package/node_modules/.pnpm/react-native@0.73.6/node_modules/react-native
   `- react-native-worklets-core ---> my-package/node_modules/.pnpm/react-native-worklets-core@1.3.3_react-native@0.73.6/node_modules/react-native-worklets-core
```
(here `--->` denotes symlink)

So when this library tries to find `node_modules` directory, it runs `node --print "require.resolve('react-native/package.json')"`, which follows symlink and returns `my-package/node_modules/.pnpm/react-native@0.73.6/node_modules/react-native/package.json` path, which is not correct.

## Changes

Replaced `node_modules` directory resolution through `react-native` package, with direct `"require.resolve('react-native-worklets-core')"`. This should not break any projects, because documentation says that [user needs to install `react-native-worklets-core`, in order to use frame processors](https://react-native-vision-camera.com/docs/guides/frame-processors#installation). This means that `react-native-worklets-core` should always be found by nodejs.

## Tested on

* iPhone 12 Pro Max, iOS Version 17.5.1

## Related issues

Fixes #2580

2024-07-23 13:48 UTC, mrousavy commented
Nice! Thank you

2024-07-23 13:50 UTC, mrousavy commented
This now fails to build if you don't have worklets installed. We need to find a workaround, please create a separate Ruby function in the podspec called `getWorkletsLibraryPath()`, which internally uses the code and handles the error if it cannot be found (e.g. by returning null)

![Screenshot 2024-07-23 at 15 49 27](https://github.com/user-attachments/assets/40bd2890-031f-45b7-a118-85cc9f5d9976)

2024-07-23 15:45 UTC, ArtiomTr commented
I've created function `getWorkletsLibraryPath`, it will return 'nil' if require.resolve fails

2024-07-23 19:12 UTC, mrousavy commented
I think this will still fail since it is throwing an error if the module cannot be found, it is not returning an empty string in that case. So what you want is to somehow catch that error

2024-07-23 19:15 UTC, mrousavy commented
ah lol actually it works - the error is just ignored. hmm, I still don't want users to see an error all the time

2024-07-23 19:16 UTC, mrousavy requested changes
can you try if the code I suggested works? We just catch the error if it's not found and do nothing - that way users dont see an error if they run pod install.

I haven't tried it!

2024-07-23 19:16 UTC, mrousavy commented on package/VisionCamera.podspec
> +  output = `cd "#{Pod::Config.instance.installation_root.to_s}" && node --print "require.resolve('react-native-worklets-core/package.json')"`
```suggestion
  output = `cd "#{Pod::Config.instance.installation_root.to_s}" && node --print "try { require.resolve('react-native-worklets-core/package.json') } catch (e) { /* do nothing if not found */ }"`
```

2024-07-23 19:20 UTC, ArtiomTr commented on package/VisionCamera.podspec
> +  output = `cd "#{Pod::Config.instance.installation_root.to_s}" && node --print "require.resolve('react-native-worklets-core/package.json')"`
Okey, I'll try 👍

2024-07-23 19:48 UTC, ArtiomTr commented
Yep, the suggested changes work, but now command `node --print` returns string "undefined", instead of empty string. I've updated check for that

2024-07-24 12:44 UTC, mrousavy commented
Let's go - thank you very much! I'll merge once CI goes green

2024-07-24 15:58 UTC, merged