Fix: clear orientation listener on close
cuvent/react-native-vision-camera pull request #3139
Opened 2024-08-14 14:26 UTC by ldalzottomp

## What

This PR cleans android orientation listener on camera session close.
If this is not done, the events are still fired and they accumulate until you kill the app.

## Changes

Added a `clearListeners` functions in the OrientationManager which is then called when CameraSession.close() is called.

## Tested on

Samsung Galaxy tab active4 pro. Android 14.

## Related issues

2024-08-18 02:10 UTC, Kamiss7 approved these changes

2024-08-20 21:26 UTC, mrousavy requested changes
Hey - thanks for your PR! This is good, just a few code style nitpicks.

2024-08-20 21:26 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt
> +  // remove previous listeners if attached
Can you move this comment down again to line 80 where it was before?

2024-08-20 21:26 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt
> +  fun clearListeners() {
Let's rename this to `stopUpdates`

2024-08-20 21:41 UTC, merged

2024-08-21 15:32 UTC, ldalzottomp commented
Thanks for handling the requested changes