fix: events in bridgeless mode
cuvent/react-native-vision-camera pull request #3240
Opened 2024-10-11 13:55 UTC by WoLewicki

## What

PR fixing events in bridgeless mode on Android, due to their stricter convention of naming there.

## Changes

## Tested on

## Related issues

2024-10-15 14:14 UTC, hannojg approved these changes
lgtm, thanks!

2024-10-15 14:14 UTC, mrousavy reviewed
Hey - thanks for this PR, really helpful stuff! 🙏
Just one question

2024-10-15 14:14 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/react/Events.kt
> +    const val EVENT_NAME = "topInitialized"
Why top instead of camera?

2024-10-15 14:30 UTC, hannojg commented on package/android/src/main/java/com/mrousavy/camera/react/Events.kt
> +    const val EVENT_NAME = "topInitialized"
every event needs to be prefixed with `top` now in the event emitter code. @WoLewicki Can we please rename these events to `topCameraInitialized` etc

2024-10-15 14:31 UTC, hannojg requested changes
@WoLewicki Can we please rename these events to `topCameraInitialized` (so including Camera) etc?

2024-10-15 15:13 UTC, hannojg commented
All good, already went ahead and updated the names. @mrousavy good for merge!

2024-10-15 15:18 UTC, WoLewicki commented
@hannojg are you sure it works? I remember having some problems with such renaming, I think it is due to JS callbacks not having `camera` in their name. Maybe wait with merging it and let me double-check ok?

2024-10-15 16:10 UTC, hannojg commented
I tested it with the renaming and it was working in the example app, so should be good 😊  If you have the time feel free to double check ofc 🫶

2024-10-15 18:19 UTC, hannojg approved these changes

2024-10-16 09:06 UTC, mrousavy requested changes

2024-10-16 09:06 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/react/CameraViewManager.kt
> +      .put(AverageFpsChangedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onCodeScanned"))
These 5 events are wrong. Please correct the names

2024-10-16 09:06 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/react/Events.kt
> +    const val EVENT_NAME = "topAverageFpsChanged"
```suggestion
    const val EVENT_NAME = "topCameraAverageFpsChanged"
```

2024-10-16 09:07 UTC, mrousavy commented on package/android/src/main/java/com/mrousavy/camera/react/CameraViewManager.kt
> +      .put(AverageFpsChangedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onCodeScanned"))
```suggestion
      .put(CameraPreviewStartedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onPreviewStarted"))
      .put(CameraPreviewStoppedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onPreviewStopped"))
      .put(CameraOutputOrientationChangedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onOutputOrientationChanged"))
      .put(CameraPreviewOrientationChangedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onPreviewOrientationChanged"))
      .put(AverageFpsChangedEvent.EVENT_NAME, MapBuilder.of("registrationName", "onAverageFpsChanged"))
```

2024-10-16 09:08 UTC, mrousavy commented
I committed the changes to fix the wrong names - @hannojg if you already have the test setup running could you maybe test if everything still works? Especially onPreviewStarted and onPreviewStopped

2024-10-16 09:09 UTC, hannojg commented
Sure, let me test, one second

2024-10-16 09:16 UTC, hannojg commented
![Screenshot 2024-10-16 at 11 16 05](https://github.com/user-attachments/assets/02d221c3-8126-4c1f-afd2-6ca88c9ab0bd)

yes, everything is still working on android!

2024-10-16 09:19 UTC, mrousavy approved these changes

2024-10-16 09:19 UTC, mrousavy commented
Awesome - LGTM then - thanks @WoLewicki & @hannojg !!! ❤️

2024-10-16 09:19 UTC, merged

2024-10-16 10:28 UTC, WoLewicki commented
Hey guys, did you test it in bridgeless mode? It's where the issue exists, as mentioned in the PR title. It's much stricter than bridge mode. cc @hannojg

2024-10-16 10:34 UTC, hannojg commented
Will do those tests in a moment, yes! We'll handle everything in a separate PR for new arch 😊 !

2024-10-17 14:15 UTC, hannojg commented
![Screenshot 2024-10-17 at 16 14 50](https://github.com/user-attachments/assets/70f3c277-166d-4ed5-a20b-2ff2703d7e52)

Working fine in bridgeless mode!