feat: Add `pixelFormat` field
cuvent/react-native-vision-camera pull request #559
Opened 2021-10-27 22:05 UTC by thomas-coldwell

## What

This PR adds support to include the pixel format code as part of the camera device format object on iOS. This is useful if you need to select a specific format for frame processors such as is required when using MLKit: https://developers.google.com/ml-kit/reference/ios/mlkitvision/api/reference/Classes/MLKVisionImage#parameters_1

## Changes

Adds an extra field on the `device.format` called `mediaSubType` that will hold the pixel format e.g. 420v, 420f

## Tested on

iPad 8, iOS 14.4.2

## Related issues

2021-10-28 07:12 UTC, mrousavy requested changes
Thanks for the PR Thomas! DM me on Discord if you need help or have any questions

2021-10-28 07:12 UTC, mrousavy commented on ios/CameraViewManager.swift
> +            return dict
This entire thing should be moved to `AVCaptureDevice.+toDictionary`:

https://github.com/mrousavy/react-native-vision-camera/blob/7206a794a9e1a2da4def7fdf4d8a70c9eb7f43ff/ios/Extensions/AVCaptureDevice.Format%2BtoDictionary.swift#L50

2021-10-28 07:12 UTC, mrousavy commented on src/CameraDevice.ts
> +  mediaSubType?: string;
I would prefer to make it non-optional. Every Camera has a format, that includes iPhones before iOS 13.0, and Android. So on those devices, find out what their default value is and use that. (Put in the `else` of the `if #available` on iOS, and into `CameraViewModule.getAvailableCameraDevices` on Android)

2021-10-28 07:12 UTC, mrousavy commented
Maybe also rename `mediaSubType` -> `pixelFormat`?

2021-10-28 07:16 UTC, mrousavy commented
Oh and lastly - use the C-style method. That one is also available before iOS 13.:

```swift
let mediaSubType = CMFormatDescriptionGetMediaSubType(format.formatDescription)
```

2021-10-28 11:57 UTC, mrousavy requested changes

2021-10-28 11:57 UTC, mrousavy commented on src/CameraDevice.ts
> +  pixelFormat: string;
Do we know all possible values of `pixelFormat`? I believe Formats have `420f`, `420v` and since the latest iOS version also `420x` (compressed), so let's not use `string`, but rather a TS union.

1. Create `PixelFormat.ts`:

```ts
/**
 * Represents the pixel format of a `Frame`.
 * * `420v`: 420 YpCbCr 8 Bi-Planar Video Range
 * * `420f`: 420 YpCbCr 8 Bi-Planar Full Range
 * * `x420`: 420 YpCbCr 10 Bi-Planar Video Range
 */
export type PixelFormat = '420f' | '420v' | 'x420'
```

And in `CameraDevice.ts`:

```ts
import type { PixelFormat } from './PixelFormat'
…
pixelFormat: PixelFormat;
```

2021-10-28 11:57 UTC, mrousavy commented on ios/Extensions/FourCharCode+toString.swift
> +        return (s)
isn't that reverted? so `f024` instead of `420f`? I found [this code](https://gist.github.com/patrickjuchli/d1b07f97e0ea1da5db09#file-fourcharcode-string-swift-L42-L49) that does the same thing in reverse order

2021-10-28 12:00 UTC, mrousavy commented on ios/Extensions/FourCharCode+toString.swift
> +        return (s)
ah nevermind that's not reverse order 🤦‍♂️

2021-10-28 13:22 UTC, thomas-coldwell commented
Thanks for the feedback Marc - will do the implementation on the Android side now and update the pixelFormat type union with a specific list of what's available on Android too 😃

2021-10-29 08:25 UTC, mrousavy commented
1. Looks like [here's some information about pixel formats on Android](https://developer.android.com/reference/android/graphics/ImageFormat#YCBCR_P010)
2. You need to run `yarn check-all` to format Swift code

2021-10-29 16:49 UTC, thomas-coldwell commented
Will make sure to run it - it altered some other swift files (that I presume were unlinted/unformated) when I ran it before and didn't want those changes to clog up the PR 😅

Bit of a noob when it comes to these different formats, but are the Image Formats there the same as Pixel Formats or is it a case of you can tell what the Pixel Format will be from the Image Format?

2021-12-10 08:44 UTC, merged